language: java
os:
  - linux
  - osx
before_install:
  - echo $JAVA_HOME
script:
  - cd "AllBanks2"
  - if [[ $TRAVIS_JDK_VERSION == "oraclejdk7" ]] ; then javac -target 1.7; fi
  - if [[ $TRAVIS_JDK_VERSION == "oraclejdk8" ]] ; then javac -target 1.8; fi
  - mvn clean test -U
notifications:
  email:
    recipients:
      - "josue.211996@outlook.com"
    on_success: change
    on_failure: always
cache:
  directories:
  - $HOME/.m2

