language: java
os:
  - linux
  - osx
env:
  matrix:
    - JAVA_MATRIX=java7Linux
    - JAVA_MATRIX=java8Linux
    - JAVA_MATRIX=javaOSX
matrix:
  exclude:
  - env: JAVA_MATRIX=java8Linux
    os: osx
  - env: JAVA_MATRIX=java7Linux
    os: osx
  - env: JAVA_MATRIX=javaOSX
    os: linux
before_install:
  - if [[ $JAVA_MATRIX == "java7Linux" ]] ; then jdk_switcher use oraclejdk7; fi
  - if [[ $JAVA_MATRIX == "java8Linux" ]] ; then jdk_switcher use oraclejdk8; fi
  - if [[ $JAVA_MATRIX == "javaOSX" ]] ; then export JAVA_HOME=/usr/lib/jvm/java-7-oracle; fi
script:
  - cd "AllBanks2"
  - mvn test
notifications:
  email:
    recipients:
      - "josue.211996@outlook.com"
    on_success: change
    on_failure: always
cache:
  directories:
  - $HOME/.m2

