language: java
os:
  - linux
  - osx
jdk:
  - oraclejdk7
  - oraclejdk8
script:
  - cd "AllBanks2"
  - mvn clean deploy
notifications:
  email:
    recipients:
      - "josue.211996@outlook.com"
    on_success: change
    on_failure: always
cache:
  directories:
  - $HOME/.m2

