language: java
jdk:
  - oraclejdk8
  - oraclejdk7
os:
  - linux
  - osx
env:
  - AB_VERSION=1.8
  - AB_VERSION=1.9
script: 
  - if [[ $AB_VERSION == "1.8" ]] ; then cd "AllBanks 1.8"; fi
  - if [[ $AB_VERSION == "1.8" ]] ; then mvn clean test -U; fi
  - if [[ $AB_VERSION == "1.9" ]] ; then cd "AllBanks 1.9"; fi
  - if [[ $AB_VERSION == "1.9" ]] ; then mvn clean test -U; fi
notifications:
  email:
    recipients:
      - "josue.211996@outlook.com"
    on_success: change
    on_failure: always
cache:
  directories:
  - maven

