language: java
jdk:
  - oraclejdk8
  - oraclejdk7
os:
  - linux
env:
  - AB_VERSION=1.9
script:
  - if [[ $AB_VERSION == "1.9" ]] ; then cd "AllBanks2"; fi
  - if [[ $TRAVIS_JDK_VERSION == "oraclejdk7" ]] ; then javac -target 1.7 -source 1.8; fi
  - if [[ $TRAVIS_JDK_VERSION == "oraclejdk8" ]] ; then javac -target 1.7 -source 1.8; fi
  - if [[ $AB_VERSION == "1.9" ]] ; then mvn clean test -U; fi
notifications:
  email:
    recipients:
      - "josue.211996@outlook.com"
    on_success: change
    on_failure: always
cache:
  directories:
  - $HOME/.m2

