language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script: 
  - cd "AllBanks 1.8"
  - mvn clean test -U
  - cd "AllBanks 1.9"
  - mvn clean test -U
notifications:
  email:
    recipients:
      - "josue.211996@outlook.com"
    on_success: change
    on_failure: always
cache:
  directories:
  - maven
