language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script: mvn clean test -U
before_install: cd "AllBanks 1.8"
install: true
notifications:
  email:
    recipients:
      - "josue.211996@outlook.com"
    on_success: change
    on_failure: always
cache:
  directories:
  - maven
