language: java
jdk:
  - oraclejdk8
  - oraclejdk7
os:
  - linux
  - osx
env:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - JAVA_HOME=/usr/lib/jvm/java-7-oracle
before_install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]] ; then 
script:
  - cd "AllBanks2"
  - if [[ $TRAVIS_JDK_VERSION == "oraclejdk7" ]] ; then javac -target 1.7; fi
  - if [[ $TRAVIS_JDK_VERSION == "oraclejdk8" ]] ; then javac -target 1.8; fi
  - mvn clean test -U
notifications:
  email:
    recipients:
      - "josue.211996@outlook.com"
    on_success: change
    on_failure: always
cache:
  directories:
  - $HOME/.m2

