name: AllBanks2
version: 1.0.6
main: me.wirlie.allbanks.AllBanks
softdepend: [WorldGuard, Towny]
commands:
  allbanks:
    description: AllBanks (Main command).
    usage: Syntax error, please use /ab ?
    aliases: [ab, abanks, allb]