name: AllBanks2
version: 1.0.4
main: me.wirlie.allbanks.AllBanks
commands:
  allbanks:
    description: AllBanks (Main command).
    usage: Syntax error, please use /ab ?
    aliases: [ab, abanks, allb]