name: AllBanks2
version: 1.1
main: me.wirlie.allbanks.AllBanks
softdepend: [WorldGuard, Towny, Residence, PlotMe]
commands:
  allbanks:
    description: AllBanks (Main command).
    usage: Syntax error, please use /ab ?
    aliases: [ab, abanks, allb]