name: AllBanks2
version: 1.2
load: POSTWORLD
main: me.wirlie.allbanks.AllBanks
softdepend: [AllBanksPlotProtection, WorldGuard, Towny, Residence]
commands:
  allbanks:
    description: AllBanks (Main command).
    usage: Syntax error, please use /ab ?
    aliases: [ab, abanks, allb]
  allbanksland:
    description: AllBanks Land, use /abland help
    usage: Syntax error, please use /abland ?
    aliases: [abland, abl, allbanksl]
  plot:
    description: AllBanks Land (Short Command)
    usage: Syntax error, please use /abland ?
    aliases: [plt]
  allbanksshop:
    description: AllBanks Shop, use /abs help
    usage: Syntax error, please use /abs ?
    aliases: [abshop, allshop, alls, abs]