name: AllBanks2
version: 1.1.4
load: POSTWORLD
main: me.wirlie.allbanks.AllBanks
softdepend: [AllBanksPlotProtection, WorldGuard, Towny, Residence]
commands:
  allbanks:
    description: AllBanks (Main command).
    usage: Syntax error, please use /ab ?
    aliases: [ab, abanks, allb]
