name: AllBanks2
version: 1.1.1
load: POSTWORLD
main: me.wirlie.allbanks.AllBanks
softdepend: [WorldGuard, Towny, Residence]
commands:
  allbanks:
    description: AllBanks (Main command).
    usage: Syntax error, please use /ab ?
    aliases: [ab, abanks, allb]
  allbanksland:
    description: AllBanks Land, use /abland help
    usage: Syntax error, please use /abland ?
    aliases: [abland, abl, allbanksl]
