cfg-version: "v1.0"
pl:
  language: "EsMx"
banks:
  bank-loan:
    #Interest (in percent) for the loan. (For example 2% -> 5000 = 100)
    interest: 2
    #How much can a player borrow? (Default: 5000)
    max-loan: 5000
    #This configuration accept these "time values": day(s), hour(s), minute(s), second(s)
    #You can set multiple time values, for example: "1 days, 20 hours, 15 minutes, 1 second" = (1440 * 60) + (1200 * 60) + (15 * 60) + 1 = 156901 seconds.
    collect-interest-every: "0 days, 24 hours, 0 minutes, 0 seconds"
  bank-money:
    # How much money can save the player in the bank?
    # -1 = unlimited
    max-money-player-can-save: -1
  bank-time:
    # Pay $1 per minute. Example: 10 minutes = 10 x 1 = $10
    pay-per-minute: 1.00
    # Add one minute every 60 seconds.
    add-minute-every: 60