package me.wirlie.allbanks.land;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;

import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.TreeType;
import org.bukkit.WorldCreator;
import org.bukkit.block.Biome;
import org.bukkit.command.CommandSender;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.scheduler.BukkitRunnable;

import me.wirlie.allbanks.AllBanks;
import me.wirlie.allbanks.StringsID;
import me.wirlie.allbanks.Translation;
import me.wirlie.allbanks.utils.DataBaseUtil;
import me.wirlie.allbanks.utils.Util;
import me.wirlie.allbanks.utils.WorldGenerator;

public class AllBanksWorld {
	
	private static final File WORLDS_DATA_FOLDER = new File(AllBanks.getInstance() + File.separator + "Worlds");
	private static final Connection DBC = AllBanks.getSQLConnection("AllBanksLand");
	
	public enum WorldGenerationResult{
		SUCCESS,
		ERROR_WORLD_ID_ALREADY_EXISTS,
		ERROR_IO_EXCEPTION,
		ERROR_DATABASE_EXCEPTION,
	}
	
	private static HashMap<String, AllBanksWorld> storedMaps = new HashMap<String, AllBanksWorld>();
	
	
	public static class WorldGenerationCfg{
		public int world_height = 60;
		
		public int plot_size = 50;
		public int road_size = 10;
		public Material road_material = Material.WOOD;
		
		public boolean coal_ore = true;
		public boolean iron_ore = true;
		public boolean emerald_ore = true;
		public boolean diamon_ore = true;
		public boolean redstone_ore = true;
		public boolean gold_ore = true;
		public boolean lapis_ore = true;
		
		public boolean generate_grass = true;
		
		public boolean generate_tree = true;
		public TreeType tree_type_1 = TreeType.TREE;
		public TreeType tree_type_2 = TreeType.BIRCH;
		
		public Biome default_biome = Biome.PLAINS;
		
		String id = "";
		
		WorldGenerationCfg(String worldID){
			this.id = worldID;
			
			File worldFileCfg = new File(WORLDS_DATA_FOLDER + File.separator + worldID + "-generated-data.yml");
			
			if(!worldFileCfg.exists()){
				try {
					worldFileCfg.createNewFile();
				} catch (IOException e) {
					e.printStackTrace();
				}
				
				YamlConfiguration worldCfg = YamlConfiguration.loadConfiguration(worldFileCfg);
				
				worldCfg.set("A-IMPORTANT:", "Please do not edit this file, this file only is used for reference. This not take any effect on your generated world.");
				
				FileConfiguration cfg = AllBanks.getInstance().getConfig();
				
				world_height = cfg.getInt("allbanks-land.world-block-height", world_height);
				worldCfg.set("generated-settings.world-block-height", world_height);
				plot_size = cfg.getInt("allbanks-land.plot_size", plot_size);
				worldCfg.set("generated-settings.plot_size", plot_size);
				road_size = cfg.getInt("allbanks-land.road_size", road_size);
				worldCfg.set("generated-settings.road_size", road_size);
				
				Material road_material_try = Material.getMaterial(cfg.getString("allbanks-land.road-material", "undefined"));
				
				if(road_material_try  != null) road_material = road_material_try;
				
				worldCfg.set("generated-settings.road_material", road_material);
				
				coal_ore = cfg.getBoolean("allbanks-land.generate-ores.coal", coal_ore);
				worldCfg.set("generated-settings.chunk-generation.ores.coal", coal_ore);
				iron_ore = cfg.getBoolean("allbanks-land.generate-ores.iron", iron_ore);
				worldCfg.set("generated-settings.chunk-generation.ores.iron", iron_ore);
				emerald_ore = cfg.getBoolean("allbanks-land.generate-ores.emerald", emerald_ore);
				worldCfg.set("generated-settings.chunk-generation.ores.emerald", emerald_ore);
				diamon_ore = cfg.getBoolean("allbanks-land.generate-ores.diamond", diamon_ore);
				worldCfg.set("generated-settings.chunk-generation.ores.diamond", diamon_ore);
				redstone_ore = cfg.getBoolean("allbanks-land.generate-ores.redstone", redstone_ore);
				worldCfg.set("generated-settings.chunk-generation.ores.redstone", redstone_ore);
				gold_ore = cfg.getBoolean("allbanks-land.generate-ores.gold", gold_ore);
				worldCfg.set("generated-settings.chunk-generation.ores.gold", gold_ore);
				lapis_ore = cfg.getBoolean("allbanks-land.generate-ores.lapis", lapis_ore);
				worldCfg.set("generated-settings.chunk-generation.ores.lapis", lapis_ore);
				
				generate_grass = cfg.getBoolean("allbanks-land.generate-grass", generate_grass);
				worldCfg.set("generated-settings.chunk-generation.grass", generate_grass);
				
				generate_tree = cfg.getBoolean("allbanks-land.generate-tree-type.enable", generate_tree);
				worldCfg.set("generated-settings.chunk-generation.tree", generate_tree);
				
				TreeType tryType1 = TreeType.valueOf(cfg.getString("allbanks-land.generate-tree-type.type-1", "undefined"));
				TreeType tryType2 = TreeType.valueOf(cfg.getString("allbanks-land.generate-tree-type.type-2", "undefined"));
			
				if(tryType1 != null) tree_type_1 = tryType1;
				if(tryType2 != null) tree_type_2 = tryType2;
				
				worldCfg.set("generated-settings.chunk-generation.tree-type1", tree_type_1);
				worldCfg.set("generated-settings.chunk-generation.tree-type2", tree_type_2);
				
				Biome tryBiome = Biome.valueOf(cfg.getString("allbanks-land.default-biome", "undefined"));

				if(tryBiome != null) default_biome = tryBiome;

				worldCfg.set("generated-settings.chunk-generation.biome-def", default_biome);
				
				try {
					worldCfg.save(worldFileCfg);
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
			
		}
	}
	
	public static AllBanksWorld getPlotWorld(String worldID){
		return storedMaps.get(worldID);
	}
	
	public static boolean unloadPlotWorld(String worldID, boolean saveWorld){
		if(Bukkit.unloadWorld(worldID, saveWorld)){
			storedMaps.remove(worldID);
			return true;
		}
		
		return false;
	}
	
	public static int removePlotWorldFolder(String worldID){
		//Remover carpeta
		File worldFolder = new File(new File("").getAbsolutePath() + File.separator + worldID);
		
		if(!worldFolder.exists()) return -2;
		
		//Eliminar tabla para este mundo
				Statement stm = null;
				try {
					stm = DBC.createStatement();
					stm.executeUpdate("DROP TABLE IF EXISTS world_" + worldID + "_plots");
				} catch (SQLException e) {
					e.printStackTrace();
					return -1;
				} finally {
					if(stm != null)
						try {
							stm.close();
						} catch (SQLException e) {
							DataBaseUtil.checkDatabaseIsLocked(e);
						}
				}
		
		if(Util.deleteDirectory(worldFolder)){
			storedMaps.remove(worldID);
			return 1;
		}else{
			return 0;
		}
	}
	
	public static boolean checkPlotWorld(String worldID){
		return storedMaps.containsKey(worldID);
	}
	
	public static WorldGenerationResult generatePlotWorld(String worldID){
		return generatePlotWorld(worldID, null);
	}
	
	public static WorldGenerationResult generatePlotWorld(final String worldID, final CommandSender sender){
		if(checkPlotWorld(worldID)){
			return WorldGenerationResult.ERROR_WORLD_ID_ALREADY_EXISTS;
		}
		
		if(!WORLDS_DATA_FOLDER.exists()) WORLDS_DATA_FOLDER.mkdirs();
		
		File worldConfigurationFile = new File(WORLDS_DATA_FOLDER + File.separator + worldID + ".yml" );
		
		try {
			worldConfigurationFile.createNewFile();
		} catch (IOException e) {
			e.printStackTrace();
			return WorldGenerationResult.ERROR_IO_EXCEPTION;
		}
		
		//Crear tabla para este mundo
		Statement stm = null;
		try {
			stm = DBC.createStatement();
			stm.executeUpdate("CREATE TABLE IF NOT EXISTS world_" + worldID + "_plots (id INTEGER PRIMARY KEY AUTOINCREMENT, allbanks_coord TEXT NOT NULL, first_bound_loc TEXT NOT NULL, second_bound_loc)");
		} catch (SQLException e) {
			e.printStackTrace();
			return WorldGenerationResult.ERROR_DATABASE_EXCEPTION;
		} finally {
			if(stm != null)
				try {
					stm.close();
				} catch (SQLException e) {
					DataBaseUtil.checkDatabaseIsLocked(e);
				}
		}
		
		//Bien, comenzar a generar mundo
		WorldCreator wc = new WorldCreator(worldID);
		wc.generateStructures(false);
		wc.generator(WorldGenerator.getDefaultWorldGenerator(new WorldGenerationCfg(worldID), "AllBanksPlotGenerator"));
		
		final WorldCreator wc_final = wc;
		
		new BukkitRunnable(){

			public void run() {
				Bukkit.getServer().createWorld(wc_final);	
				if(sender != null) Translation.getAndSendMessage(sender, StringsID.COMMAND_LAND_GENERATE_WORLD_GENERATING_FINISH, Translation.splitStringIntoReplaceHashMap(">>>", "%1%>>>" + worldID), true);
			}
			
		}.runTaskAsynchronously(AllBanks.getInstance());
		
		storedMaps.put(worldID, new AllBanksWorld());
		
		return WorldGenerationResult.SUCCESS;
		
	}
	
}
